#!/usr/bin/env node
// Self-check for this standard repo. The standard must pass its own doc-system gates.
// Usage: node checks/check.mjs

import { readFile, readdir, stat } from 'node:fs/promises';
import { join, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const failures = [];
const warnings = [];

const fail = (code, msg) => failures.push(`${code}: ${msg}`);
const warn = (code, msg) => warnings.push(`${code}: ${msg}`);

async function readText(p) {
  return readFile(join(ROOT, p), 'utf8');
}

async function listMarkdown(dir = '.', acc = []) {
  const entries = await readdir(join(ROOT, dir), { withFileTypes: true });
  for (const e of entries) {
    if (e.name.startsWith('.') || e.name === 'node_modules') continue;
    const rel = dir === '.' ? e.name : `${dir}/${e.name}`;
    if (e.isDirectory()) await listMarkdown(rel, acc);
    else if (e.name.endsWith('.md')) acc.push(rel);
  }
  return acc;
}

// --- catalog ↔ files -------------------------------------------------------
const catalog = JSON.parse(await readText('catalog.json'));
const gatesDoc = JSON.parse(await readText('gates.json'));
const dimensionIds = new Set(catalog.dimensions.map((d) => d.id));

for (const d of catalog.dimensions) {
  try {
    await stat(join(ROOT, d.path));
  } catch {
    fail('CATALOG-MISSING', `catalog lists ${d.path} but the file does not exist`);
  }
}

if (catalog.version !== gatesDoc.version) {
  fail('VERSION-DRIFT', `catalog.json ${catalog.version} != gates.json ${gatesDoc.version}`);
}

// --- gate ids are two-way consistent with dimension docs -------------------
const seen = new Set();
for (const g of gatesDoc.gates) {
  if (seen.has(g.id)) fail('GATE-DUP', `duplicate gate id ${g.id}`);
  seen.add(g.id);
  if (!dimensionIds.has(g.dimension)) {
    fail('GATE-ORPHAN', `${g.id} points at unknown dimension "${g.dimension}"`);
    continue;
  }
  if (!gatesDoc.severities[g.severity]) fail('GATE-SEVERITY', `${g.id} has unknown severity ${g.severity}`);
  if (!gatesDoc.stages[g.stage]) fail('GATE-STAGE', `${g.id} has unknown stage ${g.stage}`);
  const doc = await readText(`dimensions/${g.dimension}.md`);
  if (!doc.includes(g.id)) {
    fail('GATE-UNDOCUMENTED', `${g.id} is in gates.json but not written in dimensions/${g.dimension}.md`);
  }
}

// every checklist item in a dimension must carry an id
for (const d of catalog.dimensions) {
  const doc = await readText(d.path);
  const items = doc.split('\n').filter((l) => /^- \[[ x]\]/.test(l));
  for (const line of items) {
    if (!/`[A-Z]+-\d+`/.test(line)) {
      fail('GATE-UNNUMBERED', `${d.path}: checklist item without gate id -> ${line.trim().slice(0, 60)}`);
    } else {
      const id = line.match(/`([A-Z]+-\d+)`/)[1];
      if (!seen.has(id)) fail('GATE-UNREGISTERED', `${d.path}: ${id} is not in gates.json`);
    }
  }
}

// --- doc-system rules applied to ourselves --------------------------------
const mdFiles = await listMarkdown();

for (const f of mdFiles) {
  if (/最新|latest-version|FINAL/i.test(f)) {
    fail('DOC-5', `file name suggests a moving target: ${f}`);
  }
  const text = await readText(f);

  // duplicate top-level headings (the drift that hit README once)
  const headings = text.split('\n').filter((l) => /^##\s+\S/.test(l)).map((l) => l.trim());
  const dupes = headings.filter((h, i) => headings.indexOf(h) !== i);
  if (dupes.length) fail('DOC-DUP-HEADING', `${f}: repeated heading ${[...new Set(dupes)].join(', ')}`);

  for (const line of text.split('\n')) {
    if (/^#{1,6}\s.*最新/.test(line)) fail('DOC-5', `${f}: heading claims 最新 -> ${line.trim()}`);
  }

  // relative links must resolve
  for (const m of text.matchAll(/\[[^\]]*\]\((\.\.?\/[^)#\s]+)/g)) {
    const target = resolve(dirname(join(ROOT, f)), m[1]);
    try {
      await stat(target);
    } catch {
      fail('LINK-DEAD', `${f}: dead relative link ${m[1]}`);
    }
  }

  // secrets must never live here
  if (/\b(sk-[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{12,}|ghp_[A-Za-z0-9]{20,})\b/.test(text)) {
    fail('SECRET', `${f}: looks like a credential`);
  }
  if (/\b\d{1,3}(\.\d{1,3}){3}\b/.test(text) && !/0\.0\.0\.0|127\.0\.0\.1/.test(text)) {
    warn('HOST-IN-DOC', `${f}: contains a bare IP address`);
  }
}

// --- STATUS must be generated ---------------------------------------------
try {
  const status = await readText('STATUS.md');
  if (!/Generated by/.test(status)) fail('DOC-2', 'STATUS.md is missing the generated banner');
  if (!status.includes(catalog.version)) {
    fail('DOC-2', `STATUS.md does not show catalog version ${catalog.version} — run npm run status`);
  }
} catch {
  fail('DOC-2', 'STATUS.md is missing — run npm run status');
}

// --- report ---------------------------------------------------------------
const rel = (p) => relative(process.cwd(), p) || '.';
console.log(`ship-standard self-check (${rel(ROOT)})`);
console.log(`  dimensions: ${catalog.dimensions.length}`);
console.log(`  gates:      ${gatesDoc.gates.length}`);
console.log(`  markdown:   ${mdFiles.length}`);

for (const w of warnings) console.log(`  warn  ${w}`);
for (const f of failures) console.log(`  FAIL  ${f}`);

if (failures.length) {
  console.log(`\n${failures.length} blocking problem(s).`);
  process.exit(1);
}
console.log(`\nall gates green${warnings.length ? ` (${warnings.length} warning)` : ''}.`);
