#!/usr/bin/env node
// Generates STATUS.md from catalog.json + gates.json. Never hand-edit STATUS.md.

import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = async (p) => JSON.parse(await readFile(join(ROOT, p), 'utf8'));

const catalog = await read('catalog.json');
const gatesDoc = await read('gates.json');

const byStage = new Map();
const byDimension = new Map();
for (const g of gatesDoc.gates) {
  byStage.set(g.stage, (byStage.get(g.stage) ?? 0) + 1);
  const d = byDimension.get(g.dimension) ?? { block: 0, warn: 0 };
  d[g.severity] += 1;
  byDimension.set(g.dimension, d);
}

const stageRows = Object.keys(gatesDoc.stages)
  .map((s) => `| \`${s}\` | ${byStage.get(s) ?? 0} | ${gatesDoc.stages[s]} |`)
  .join('\n');

const dimRows = catalog.dimensions
  .map((d) => {
    const c = byDimension.get(d.id) ?? { block: 0, warn: 0 };
    return `| [${d.id}](${d.path}) | ${d.status} | ${c.block} | ${c.warn} |`;
  })
  .join('\n');

const out = `# STATUS

> Generated by \`checks/render-status.mjs\`. Do not edit by hand — change \`catalog.json\` / \`gates.json\` / the dimension docs instead.

Standard version: \`${catalog.version}\`

## Gates by dimension

| Dimension | Status | block | warn |
|-----------|--------|-------|------|
${dimRows}
| **total** | — | **${gatesDoc.gates.filter((g) => g.severity === 'block').length}** | **${gatesDoc.gates.filter((g) => g.severity === 'warn').length}** |

## Gates by stage

| Stage | Gates | Meaning |
|-------|-------|---------|
${stageRows}

## How to use

- 引用门禁请用 id（例如 \`PATH-3\`），不要引用行号或段落标题。
- 豁免写在产品仓的 \`product/waivers.md\`，必须有到期日；见 [build-standard](https://github.com/miounet11/build-standard)。
- 想知道「怎么创建」而不是「能不能上线」，去 build-standard。
`;

await writeFile(join(ROOT, 'STATUS.md'), out);
console.log(`wrote STATUS.md (${gatesDoc.gates.length} gates, version ${catalog.version})`);
